### ISSUE TITLE
Cant run the mc2d

### ISSUE THREAD

**Issue by lloootsop** [Den4200/mc2d#1]
Im trying to run your game, but seems like i cant... Need to install anything?
![Screenshot from 2020-04-14 14-48-42](https://user-images.githubusercontent.com/61469147/79232241-2a022d00-7e5f-11ea-8c91-256c5d81af04.png)

**Comment by Den4200** [comment]
Hello there. Once you have pipenv installed, just run `pipenv sync` to install dependencies and `pipenv run mc2d` to run the game. Make sure you are in the root directory of the repository when doing this.

Keep in mind that if you explore too around the world a lot, many chunks will load into the world. This’ll cause some lag since the chunks are not yet dynamically despawned. This is being worked on in another branch.
